term.setBackgroundColor(colors.black)
term.clear()
term.setTextColor(colors.white)
bigfont.writeOn(term.current(), 2, "Want to advertise", 5, 3)
bigfont.writeOn(term.current(), 2, "here?", 5, 13)
bigfont.writeOn(term.current(), 1, "Run your ad campaign with us.", 5, 25)
bigfont.writeOn(term.current(), 1, "Starting at \1644 per month.", 5, 29)
bigfont.writeOn(term.current(), 1, "DM me on Discord", 5, 37)
term.setTextColor(colors.lightGray)
bigfont.writeOn(term.current(), 1, "Nxtad #" .. os.getComputerID(), 5, 50)
